apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fos-manager-discovery
rules:
- apiGroups:
  - discovery.k8s.io
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
  - create
  - update
  - delete
