# permissions for end users to view failoverservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: failoverservice-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: failover-service-operator
    app.kubernetes.io/part-of: failover-service-operator
    app.kubernetes.io/managed-by: kustomize
  name: failoverservice-viewer-role
rules:
- apiGroups:
  - mycreepy.github.io
  resources:
  - failoverservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mycreepy.github.io
  resources:
  - failoverservices/status
  verbs:
  - get
