# permissions for end users to edit failoverservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: failoverservice-editor-role
rules:
- apiGroups:
  - mycreepy.github.io
  resources:
  - failoverservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mycreepy.github.io
  resources:
  - failoverservices/status
  verbs:
  - get
