---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - mycreepy.github.io
  resources:
  - failoverservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - mycreepy.github.io
  resources:
  - failoverservices/finalizers
  verbs:
  - update
- apiGroups:
  - mycreepy.github.io
  resources:
  - failoverservices/status
  verbs:
  - get
  - patch
  - update
