apiVersion: v1
kind: Service
metadata:
  name: sample
  namespace: default
spec:
  clusterIP: None
  selector:
    app: sample
  ports:
  - port: 8080
    targetPort: http
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sample
  namespace: default
spec:
  selector:
    matchLabels:
      app: sample
  serviceName: sample
  replicas: 2
  template:
    metadata:
      labels:
        app: sample
    spec:
      containers:
      - name: sample
        image: registry.k8s.io/nginx-slim:0.27
        ports:
        - containerPort: 80
          name: web
        readinessProbe:
          httpGet:
            port: web
            path: /
          initialDelaySeconds: 30
